// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsrrmqfeevhcfednylhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcnJtcWZlZXZoY2ZlZG55bGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NDgxNjEsImV4cCI6MjA5MDUyNDE2MX0.PDihKxF6h5bQAZZGgLvrPFCYbnNHofCZH8guoz_AIf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});